access_token: qz3ve07m0vruvsv7bcybhayo4mtueq
app:
  id: 9mle7nm0ei1nyme6722l0zzyyyxig9
  secret: zgxoy1xw3ks44ixz1igf9z3s3l4fbj
authorization_code: unnecessary
refresh_token: bd5lgzxh28gz7pe08e19wdnr2vbd51nvmjpyt87s6584fsg74v
scopes:
- chat:edit
- chat:read
